
## 2.28
```{r}
z <- matrix(0, 100, 2)

for(i in 1:100) {
  # 1. Generate Y~U(B^2(1))
  x <- rnorm(2)
  R <- runif(1)^{1/2}
  y <- x/norm(as.matrix(x)) * R
  
  # 2.Find B 
  sigma <- matrix(c(5/9, 7/6, 7/6 ,25/9), 2, 2)
  B <- chol(sigma)
  
  # 3. Z
  z[i,] <- solve(t(B)) %*% y
}

plot(z[,1], z[,2])

```

<br>
<br>
<br>
<br>
<br>
<br>

## 2.30
a) Find the one-step transition matrix for this Markov chain.
```{r}
P = matrix(c(0, 1/2, 1/2, 0, 0, 0,
             1/3, 0, 1/3, 1/3, 0, 0,
             1/4, 1/4, 0, 1/4, 1/4, 0,
             0, 1/4, 1/4, 0, 1/4, 1/4,
             0, 0, 1/3, 1/3, 0, 1/3,
             0, 0, 0, 1/2, 1/2, 0), 6, 6, byrow=T)
```

b) Show that the stationary distribution is given by π
```{r}


pi = c(1/9, 1/6, 2/9, 2/9, 1/6, 1/9)

pi %*% P == pi
```

c) simulation
```{r}



pi0 = c(1/6, 1/6, 1/6, 1/6, 1/6, 1/6)
freq = rep(0, 6)

N = 10000
x = sample(seq(1, 6), 1, prob=pi0) # x0
freq[x] = freq[x] + 1
for(i in 1:N) {
  x = sample(seq(1, 6), 1, prob=P[x, ])
  freq[x] = freq[x] + 1
}
prob = freq / (N + 1)
prob
```


