
```{r}
library("nimble")
```
#### (계산은 앞에 있습니다.)

### 6.2
약 1000번 쯤에서 stationarity를 가진다.
```{r}
set.seed(1)

Ran.walk.sampler = function(N, sigma) {
  x = c()
  x[1] = 1 # start point
  
  for(i in 2:N){
    y = x[i-1] + rnorm(1, mean=0, sd=sigma)
    alpha = min(exp(-0.5*(y-10)^2 + 0.5*(x[i-1]-10)^2) , 1)
    x[i] = ifelse(runif(1)<alpha, y, x[i-1])
  }
  return(x)
}

plot(Ran.walk.sampler(5000, 0.1), xlab="iteration", ylab="state")
```

### 6.3
```{r}
auto.cov = function(sigma, max_lag) {
  N = 100000
  k = 1000 # burn-in
  stationary = Ran.walk.sampler(N, sigma)[k:N]
  
  return(acf(stationary, lag.max = max_lag, type = 'covariance', plot = FALSE)$acf)
}

R1 = auto.cov(sigma = 0.05, max_lag = 4000)
R2 = auto.cov(sigma = 0.1, max_lag = 4000)
R3 = auto.cov(sigma = 0.2, max_lag = 4000)


plot(R1, type = 'l', ylab = 'R', lty = 1, ylim = c(-0.1, 1))
points(R2, type = 'l', lty = 2)
points(R3, type = 'l', lty = 3)
legend('topright',  legend = c('sigma = 0.05', 'sigma = 0.1', 'sigma = 0.2'),
       lty=c(1,2,3))

```

### 6.4 Independence sampler
a) lambda가 2보다 커지면 경계로 갈수록 안 맞는 값들이 생긴다. 
```{r}
N = 10^5
lambda = c(0.2,1,2,5)


Indep.sampler = function(N, lambda) {
  x = c()
  x[1] = 1 # start point
  
  for(i in 2:N){
    y = -log(runif(1))/lambda # proposal density에서 생성 
    alpha = min(exp((1-lambda)*(x[i-1]-y)) , 1)
    if (runif(1)<alpha) {x[i] = y}
    else {x[i] = x[i-1]}
  }
  return(x)
}


par(mfrow=c(2,2))

for(i in 1:4) {
  hist(Indep.sampler(N, lambda[i]), main=paste("λ =", lambda[i]), prob=T, xlab="x")  
  curve(dexp(x), add=T)
}

```

b)
- 각 $\lambda$의 20회 run에 대한 sample mean 계산 후 dotplot 그리기
```{r}
lambda = c(0.2,1,2,5)
Mean = matrix(0, nrow=20, ncol=4)

x = c()
for(i in 1:20) {
  for(j in 1:4) {
    x = Indep.sampler(10000, lambda[j])
    Mean[i,j] = mean(x)
  }  
}

par(mfrow = c(4, 1))
for(j in 1:4) {
  plot(Mean[,j], rep(0, 20), xlim = c(0.6, 1.2), xlab = '', ylab = '', 
       main = paste("λ =", lambda[j]))
}

```

- $\lambda$=5에 대한 auto-covariance

```{r}
xcov = matrix(nrow = 4001, ncol = 20) 
for (i in 1:20) {
  x4 = Indep.sampler(100000, 5)
  xcov[, i] = acf(x4, lag.max = 4000, type = 'covariance', plot = FALSE)$acf
}

plot(xcov[, 1], type = 'l', col = 'black', xlim = c(0, 4000), ylim = c(-0.1, 1))
for (i in 2:20) points(xcov[, i], type = 'l') 
abline(h = 0, type = 'l', lty = 2)
```



## 6.5
$\lambda$가 작을수록 true dist와 비슷하다.

```{r}
N = 10^5
lambda = c(0.1,1,5,20)


Ran.walk.sampler = function(lambda) {
  x = c()
  x[1] = 1 # start point
  
  for(i in 2:N){
    u = runif(1)
    r = rdexp(1, rate=lambda) # 이중지수분포에서 생성
    y = x[i-1]+r
    alpha = min(exp(x[i-1]-y)*I(y>0), 1)
    x[i] = ifelse(runif(1)<alpha, y, x[i-1])
  }
  
  return(x)
}


par(mfrow=c(2,2))

for(i in 1:4) {
  hist(Ran.walk.sampler(lambda[i]), main=paste("λ =", lambda[i]), prob=T, xlab="x")  
  curve(dexp(x, lambda[i]),
        xlim=c(0, 15), col="blue", add=T)
}

par(mfrow=c(1,1))
```
